config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

#                Prefix Verb   URI Pattern                                       Controller#Action
#                  root GET    /                                                 restaurants#index
#    restaurant_reviews POST   /restaurants/:restaurant_id/reviews(.:format)     reviews#create
# new_restaurant_review GET    /restaurants/:restaurant_id/reviews/new(.:format) reviews#new
#           restaurants GET    /restaurants(.:format)                            restaurants#index
#                       POST   /restaurants(.:format)                            restaurants#create
#        new_restaurant GET    /restaurants/new(.:format)                        restaurants#new
#       edit_restaurant GET    /restaurants/:id/edit(.:format)                   restaurants#edit
#            restaurant GET    /restaurants/:id(.:format)                        restaurants#show
#                       PATCH  /restaurants/:id(.:format)                        restaurants#update
#                       PUT    /restaurants/:id(.:format)                        restaurants#update
#                       DELETE /restaurants/:id(.:format)                        restaurants#destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, :dependent => :destroy

  validates :name, :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5, allow_nil: false }
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews

    @restaurant = Restaurant.find(params[:id])
    @review = Review.new()

  end

  def new
    @restaurant = Restaurant.new()
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new()
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant_id = params[:restaurant_id]
    @restaurant = Restaurant.find(@review.restaurant_id)
    if @review.save
      redirect_to restaurant_path(@review.restaurant_id)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form_restaurant.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  <%= f.button :submit, value: "Add restaurant", class: "btn btn-info" %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="text-center">
  <h2>Restaurants#edit</h2>
  <p>Find me in app/views/restaurants/edit.html.erb</p>
</div>

<div class="container">
  <div class="row padded">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form_restaurant' %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= link_to "Cancel edition", restaurant_path(@restaurant) %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="text-center">
  <h2>Restaurants index</h2>
  <p>All restaurants listed here</p>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <ol>

          <% @restaurants.each do |restaurant| %>
          <li><%= link_to "#{restaurant.name} - #{restaurant.address}", restaurant_path(restaurant) %></li>
          <% end %>

      </ol>
    </div>
  </div>
  <div class="row padded">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= link_to "Add a restaurant", new_restaurant_path %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="text-center">
  <h2>Restaurants#new</h2>
  <p>Find me in app/views/restaurants/new.html.erb</p>
</div>

<div class="container">
  <div class="row padded">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form_restaurant' %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= link_to "Cancel creation", restaurants_path %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="text-center">
  <h2>Restaurants#show</h2>
  <p>Find me in app/views/restaurants/show.html.erb</p>
</div>

<div class="container">
  <div class="row ">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <hr>
      <ul class="list-unstyled">
        <li><%= @restaurant.name %></li>
        <li><%= @restaurant.address %></li>
        <li><%= @restaurant.phone_number %></li>
        <li><%= @restaurant.category %></li>
      </ul>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'reviews/form_review' %>
      <hr>
    </div>

  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <ul class="list-unstyled">
        <% @reviews.each do |review| %>
          <li>Rating:

            <% review.rating.to_i.times do %>
            <%= "*" %>
            <% end %>
          </li>
          <li><%= review.content %></li>
          <li><hr></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row padded">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">

    <%= link_to "Back to index", restaurants_path %>
    ||
    <%= link_to "Delete this restaurant", restaurant_path(@restaurant), method: :Delete, data: {confirm: "Are your sure?"} %>
    ||
    <%= link_to "Edit restaurant details", edit_restaurant_path(@restaurant) %>
    ||
    <%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
    </div>
  </div>

</div>

app/views/reviews/_form_review.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.error_notification %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => %w[0 1 2 3 4 5] %>
  <%= f.button :submit, value: "Post review", class: "btn btn-info" %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="text-center">
  <h1>Reviews#new</h1>
  <p>Find me in app/views/reviews/new.html.erb</p>
</div>

<div class="container">
  <div class="row padded">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form_review' %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= link_to "Cancel creation", restaurant_path(@restaurant) %>
    </div>
  </div>
</div>